### ISSUE TITLE
add height of last update to one accounts state

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#346]
### TODO
@thepiwo Please make the necessary changes if I have missed something or wrote something wrong.
- [x] Add new field `last_updated` in Account.t() next to `nonce`. Location Account module
- [x] Provide getter and setter functionality in Account module for this field.
- [x] Provide functionality based on the transaction action to update this field
- [x] Fix test
